<?php

$static_routes = [
    # every route path should end with a slash
    null                    => ['controller' => 'NotFoundController',
                                'action'     => 'notFoundPageAction'],
    '/notfound/'            => ['controller' => 'NotFoundController',
                                'action'     => 'notFoundPageAction'],
    '/'                     => ['controller' => 'IndexController',
                                'action'     => 'indexPageAction'],
    '/login/'               => ['controller' => 'LoginController',
                                'action'     => 'loginPageAction'],
    '/login/auth/'          => ['controller' => 'LoginController',
                                'action'     => 'loginAuthAction',
                                'params'     => ['username', 'password']],
    '/logout/'              => ['controller' => 'LoginController',
                                'action'     => 'logoutAction'],
    '/register/'            => ['controller' => 'RegisterController',
                                'action'     => 'registerPageAction'],
    '/register/now/'        => ['controller' => 'RegisterController',
                                'action'     => 'registerNowAction',
                                'params'     => ['username', 'password', 'cnp']],
    '/user/'                => ['controller' => 'UserController',
                                'action'     => 'userPageAction'],
    '/admin/'                => ['controller' => 'UserController',
                                'action'     => 'adminPageAction'],
    '/doctor/'              => ['controller' => 'UserController',
                                'action'     => 'doctorPageAction'],
    '/user/edit/'           => ['controller' => 'UserController',
                                'action'     => 'userEditAction'],
    '/user/save/'           => ['controller' => 'UserController',
                                'action'     => 'userSaveAction',
                                'params'     => ['username', 'isActive', 'firstname', 'lastname', 'cnp', 'telephone']],
    '/user/status/'         => ['controller' => 'UserController',
                                'action'     => 'userStatusAction',
                                'params'     => ['idUser', 'isActive']],
    '/user/resetpassword/'  => ['controller' => 'UserController',
                                'action'     => 'resetPasswordAction',
                                'params'     => ['password', 'confirm_password']],
    '/patient/remove/'      => ['controller' => 'PatientController',
                                'action'     => 'patientRemoveAction',
                                'params'     => ['idPatient', 'fullName']],
    '/patient/{idPatient}'        => ['controller' => 'PatientController',
                                'action'     => 'patientEditPageAction',
                                'params'     => ['idPatient']],
    '/patient/save/'        => ['controller' => 'PatientController',
                                'action'     => 'patientEditSaveAction',
                                'params'     => ['idPatient', 'firstName', 'lastName', 'telephone', 'address']],
    '/patient/add/'         => ['controller' => 'PatientController',
                                'action'     => 'patientAddPageAction'],
    '/patient/add/save/'     => ['controller' => 'PatientController',
                                'action'     => 'patientAddSaveAction',
                                'params'     => ['firstName', 'lastName', 'telephone', 'address', 'cnp']],
    '/appointment/remove/'  => ['controller' => 'AppointmentController',
                                'action'     => 'appointmentRemoveAction',
                                'params'     => ['idAppointment']],
    '/appointment/add/'     => ['controller' => 'AppointmentController',
                                'action'     => 'appointmentAddPageAction'],
    '/appointment/add/save/' => ['controller' => 'AppointmentController',
                                'action'     => 'appointmentAddSaveAction',
                                'params'     => ['selectedPatient', 'startDate', 'endDate', 'selectedInterventions' ]],
    '/intervention/add/'    => ['controller' => 'InterventionController',
                                'action'     => 'interventionAddPageAction'],
    '/intervention/add/save/'  => ['controller' => 'InterventionController',
                                'action'     => 'interventionAddSaveAction',
                                'params'     => ['name', 'price' ]],
    '/intervention/remove/'  => ['controller' => 'InterventionController',
                                'action'     => 'interventionRemoveAction',
                                'params'     => ['idIntervention']],
];
