<html lang="en">

<script src="/js/jquery.min.js"></script>
<link href="/css/bootstrap.min.css" id="bootstrap-css" rel="stylesheet" type="text/css">
<script src="/js/bootstrap.min.js"></script>
<script src="/js/pooper.min.js"></script>
<link href="/css/index.css" id="index-css" rel="stylesheet" type="text/css">
<script src="/js/index.js"></script>

<div class="top-bar">
	<div class="row">
		<div class="col-md-12">
			<form id="logOut-form" action="/logout" method="post" role="form" class="float-right ml-2">
				<button type="submit" name="logOut-submit" id="logOut-submit" class="form-control btn btn-danger btn-sm">Log Out</button>
			</form>
			<form id="back-form" action="/user" method="post" role="form" class="float-right">
				<button type="submit" name="back-submit" id="back-submit" class="form-control btn btn-secondary btn-sm">Back</button>
			</form>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<form id="intervention-form" action="/intervention/add/save" method="post" role="form" class="col-md-12">
			<div class="form-row">
				<div class="form-group col-md-6">
					<label for="interventionName">Name</label>
					<input type="text" name="name" id="interventionName" tabindex="1" class="form-control" placeholder="Intervention name" required>
				</div>
				<div class="form-group col-md-6">
					<label for="interventionPrice">Price</label>
					<input type="text" name="price"
						title="Need to be a number with maximum 2 decimals"
						id="interventionPrice" pattern="\d+(\.\d{1,2})?" tabindex="2" class="form-control" placeholder="Intervention price" required>
				</div>
				<div class="form-group col-md-12">
					<button type="submit" name="intervention-submit" id="intervention-submit" tabindex="3" class="form-control btn btn-outline-primary btn-sm">Add</button>
				</div>
			</div>
		</form>
		<label class="red">
			<?php if(isset($_SESSION["generalMsg"])) {
				echo $_SESSION["generalMsg"];
				unset($_SESSION['generalMsg']);} 
			?>
		</label>
	</div>
</div>

</html>