<html lang="en">

<script src="/js/jquery.min.js"></script>
<link href="/css/bootstrap.min.css" id="bootstrap-css" rel="stylesheet" type="text/css">
<script src="/js/bootstrap.min.js"></script>
<script src="/js/pooper.min.js"></script>
<link href="/css/index.css" id="index-css" rel="stylesheet" type="text/css">
<script src="/js/index.js"></script>

<div class="top-bar">
	<div class="row">
		<div class="col-md-12">
			<form id="logOut-form" action="/logout" method="post" role="form" class="float-right ml-2">
				<button type="submit" name="logOut-submit" id="logOut-submit" class="form-control btn btn-danger btn-sm">Log Out</button>
			</form>
			<form id="back-form" action="/user" method="post" role="form" class="float-right">
				<button type="submit" name="back-submit" id="back-submit" class="form-control btn btn-secondary btn-sm">Back</button>
			</form>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<form id="addappointment-form" action="/appointment/add/save" method="post" role="form" class="col-md-12">
			<div class="form-row">
				<div class="form-group col-md-12">
				<label for="selectedPatient">Patient</label>
				<select class="form-control" name="selectedPatient" id="patientSelector" required tabindex="1">
					<option <?php if(!isset($_SESSION['addedAppointment'])) echo 'selected'?> value="">Select a patient...</option>
					<?php foreach ($_SESSION["patients"] as &$option) { ?>
						<option <?php if(isset($_SESSION['addedAppointment']) && $_SESSION['addedAppointment']['selectedPatient'] == $option['idPatient']) echo 'selected' ?> value="<?=$option["idPatient"]?>"><?=$option["lastName"]." ".$option["firstName"]." | CNP: ".$option["CNP"]?></option>
					<?php } ?>
				</select>
				</div>
				<div class="col-md-6">
					<label for="appointmentStartDate">Start Date</label>
					<input type="datetime-local" name="startDate" id="appointmentStartDate" onchange="appointmentStartDateChanged()" tabindex="2" class="form-control" required>
				</div>
				<div class="col-md-6">
					<label for="appointmentEndDate">End Date</label>
					<input type="datetime-local" name="endDate" id="appointmentEndDate" tabindex="3" class="form-control" disabled required>
				</div>
				<div class="form-group col-md-6">
					<label for="selectedInterventions" class="d-block">Interventions:</label>
					<?php foreach ($_SESSION["interventions"] as &$intervention) { ?>
						<input <?php if(isset($_SESSION['addedAppointment']) && in_array($intervention["idIntervention"], $_SESSION['addedAppointment']['selectedInterventions'])) echo 'checked' ?> type="checkbox" name="selectedInterventions[<?=$intervention["idIntervention"]?>]" value="<?=$intervention["idIntervention"]?>"> <?=$intervention["name"].' - '.$intervention["price"]?><br>
					<?php } ?>
				</div>
				
				<div class="form-group col-md-12">
					<button type="submit" name="addappointment-submit" id="addappointment-submit" tabindex="5" class="form-control btn btn-outline-primary btn-sm">Add</button>
				</div>
			</div>
		</form>
		<label class="red">
			<?php if(isset($_SESSION["generalMsg"])) {
				echo $_SESSION["generalMsg"];
				unset($_SESSION['generalMsg']);} 
			?>
		</label>
	</div>
</div>

</html>