<html lang="en">

<script src="/js/jquery.min.js"></script>
<link href="/css/bootstrap.min.css" id="bootstrap-css" rel="stylesheet" type="text/css">
<script src="/js/bootstrap.min.js"></script>
<script src="/js/pooper.min.js"></script>
<link href="/css/index.css" id="index-css" rel="stylesheet" type="text/css">
<script src="/js/index.js"></script>

<div class="container">
    	<div class="row">
			<div class="col-md-12 d-flex flex-column align-items-center">
				<h1 class="red">404 NOT FOUND</h1>
				<h4>You are not authorized to view this page or this page don't exist!</h4>
			</div>
			
	</div>
</html>